# SPDX-License-Identifier: Apache-2.0

name: 'SBOM Scan'
description: 'Scan SBOM for known vulnerabilities using Software Composition Analysis (SCA)'

inputs:
  sbom-file:
    description: 'Path to the SBOM file to scan'
    required: true
  fail-on-severity:
    description: 'Fail on vulnerability severity (negligible, low, medium, high, critical)'
    required: false
    default: 'high'
  output-format:
    description: 'Output format for vulnerability report (table, json, sarif, cyclonedx)'
    required: false
    default: 'table'
  output-file:
    description: 'Output file name for the vulnerability report'
    required: false
    default: 'vulnerability-report.txt'
  grype-version:
    description: 'Version of Grype to use'
    required: false
    default: 'v0.104.3'
  upload-artifact:
    description: 'Whether to upload the vulnerability report as a GitHub artifact'
    required: false
    default: 'true'

outputs:
  report-path:
    description: 'Path to the vulnerability report'
    value: ${{ steps.scan.outputs.report-path }}
  vulnerabilities-found:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.scan.outputs.vulnerabilities-found }}
  critical-count:
    description: 'Number of critical vulnerabilities'
    value: ${{ steps.scan.outputs.critical-count }}
  high-count:
    description: 'Number of high vulnerabilities'
    value: ${{ steps.scan.outputs.high-count }}

runs:
  using: 'composite'
  steps:
    - name: Install Grype
      shell: bash
      run: |
        echo "::group::Installing Grype ${{ inputs.grype-version }}"
        INSTALL_URL="https://raw.githubusercontent.com/anchore/grype/main/install.sh"
        curl -sSfL "$INSTALL_URL" | sh -s -- -b /usr/local/bin ${{ inputs.grype-version }}
        grype version
        echo "::endgroup::"

    - name: Scan SBOM for Vulnerabilities
      id: scan
      shell: bash
      run: |
        echo "::group::Scanning SBOM for vulnerabilities"
        mkdir -p reports

        REPORT_FILE="reports/${{ inputs.output-file }}"

        if [ ! -f "${{ inputs.sbom-file }}" ]; then
          echo "❌ SBOM file not found: ${{ inputs.sbom-file }}"
          exit 1
        fi

        echo "Scanning SBOM for vulnerabilities..."
        echo "SBOM file: ${{ inputs.sbom-file }}"
        echo "Fail on severity: ${{ inputs.fail-on-severity }}"

        # Run Grype scan
        set +e
        grype sbom:"${{ inputs.sbom-file }}" \
          --output "${{ inputs.output-format }}" \
          --file "$REPORT_FILE" \
          --fail-on "${{ inputs.fail-on-severity }}"
        SCAN_EXIT_CODE=$?
        set -e

        # Generate JSON report for parsing
        grype sbom:"${{ inputs.sbom-file }}" \
          --output json \
          --file "reports/vulnerability-report.json" || true

        # Parse vulnerability counts
        JSON_REPORT="reports/vulnerability-report.json"
        if [ -f "$JSON_REPORT" ]; then
          VULN_COUNT=$(jq '[.matches[]] | length' "$JSON_REPORT" 2>/dev/null || echo "0")
          CRITICAL_COUNT=$(jq '[.matches[] | select(.vulnerability.severity == "Critical")] | \
            length' "$JSON_REPORT" 2>/dev/null || echo "0")
          HIGH_COUNT=$(jq '[.matches[] | select(.vulnerability.severity == "High")] | \
            length' "$JSON_REPORT" 2>/dev/null || echo "0")
          MEDIUM_COUNT=$(jq '[.matches[] | select(.vulnerability.severity == "Medium")] | \
            length' "$JSON_REPORT" 2>/dev/null || echo "0")
          LOW_COUNT=$(jq '[.matches[] | select(.vulnerability.severity == "Low")] | \
            length' "$JSON_REPORT" 2>/dev/null || echo "0")
        else
          VULN_COUNT=0
          CRITICAL_COUNT=0
          HIGH_COUNT=0
          MEDIUM_COUNT=0
          LOW_COUNT=0
        fi

        echo "report-path=$REPORT_FILE" >> $GITHUB_OUTPUT
        echo "vulnerabilities-found=$VULN_COUNT" >> $GITHUB_OUTPUT
        echo "critical-count=$CRITICAL_COUNT" >> $GITHUB_OUTPUT
        echo "high-count=$HIGH_COUNT" >> $GITHUB_OUTPUT

        echo ""
        echo "🔍 Vulnerability Scan Summary:"
        echo "  Total Vulnerabilities: $VULN_COUNT"
        echo "  Critical: $CRITICAL_COUNT"
        echo "  High: $HIGH_COUNT"
        echo "  Medium: $MEDIUM_COUNT"
        echo "  Low: $LOW_COUNT"

        if [ $CRITICAL_COUNT -gt 0 ] || [ $HIGH_COUNT -gt 0 ]; then
          echo "::warning::Found $CRITICAL_COUNT critical and $HIGH_COUNT high severity vulnerabilities"
        fi

        echo "::endgroup::"

        # Exit with the original Grype exit code
        exit $SCAN_EXIT_CODE

    - name: Upload Vulnerability Report
      if: always() && inputs.upload-artifact == 'true'
      uses: actions/upload-artifact@v6.0.0
      with:
        name: vulnerability-report
        path: reports/
        retention-days: 90
        if-no-files-found: warn
