# https://getsops.io/

creation_rules:
  # 1. Dotenv files: encrypt only secrets-like keys, preserve non-sensitive config
  - path_regex: '(^|/)\.env(\..*)?$'
    input_type: dotenv
    encrypted_regex: "(?i)(secret|password|token|apikey|api_key|key|credential|pass)"
    key_groups:
      - pgp:
          - "0F0FA4800EFAD0BE36B109AE7F34A16A052377E8" # sops
          - "BC848B1B830AE75F4803FD4962B67BF77576F6AE" # sops-percent

  # 2. Certificates and Private Keys
  - path_regex: '.*\.(pem|key|crt|cer|p12|der)$'
    input_type: binary
    key_groups:
      - pgp:
          - "0F0FA4800EFAD0BE36B109AE7F34A16A052377E8" # sops
          - "BC848B1B830AE75F4803FD4962B67BF77576F6AE" # sops-percent

  # 3.1. Generic group rule
  - key_groups:
      - pgp:
          - "0F0FA4800EFAD0BE36B109AE7F34A16A052377E8" # sops
          - "BC848B1B830AE75F4803FD4962B67BF77576F6AE" # sops-percent

  # 3.2. Generic single rule
  - pgp: "BC848B1B830AE75F4803FD4962B67BF77576F6AE" # sops-percent
