# SPDX-License-Identifier: Apache-2.0

name: Conftest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conftest:
    name: Conftest Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Conftest
        uses: sentenz/actions/conftest@bceed480720a7bc304e974cd655ebe42ac41d5e2 # 1.1.9
        with:
          policy-path: "./tests/policy"
