# SPDX-License-Identifier: Apache-2.0

name: Conftest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conftest:
    name: Conftest Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Conftest
        uses: sentenz/actions/conftest@c393f1ada4c285deb9408247138486bbc773b7fe # 1.4.0
        with:
          policy-path: "./tests/policy"
