# SPDX-License-Identifier: Apache-2.0

name: Regal

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Regal
        uses: sentenz/actions/regal@d3b0a0d59ac008f6918c5d8304acab2c9d1abbf2 # 1.4.3
        with:
          path: "./tests/policy"
          regal-version: "latest"
