# SPDX-License-Identifier: Apache-2.0

name: Regal

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Regal
        uses: sentenz/actions/regal@13459d04f1c048f60ffc99d50dba5a362111d7b2 # 1.4.4
        with:
          path: "./tests/policy"
          regal-version: "latest"
