# SPDX-License-Identifier: Apache-2.0

name: Renovate

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 4:00 AM UTC
    - cron: "0 4 * * 0"

jobs:
  renovate:
    name: Renovate Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      checks: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Renovate
        uses: sentenz/actions/renovate@c393f1ada4c285deb9408247138486bbc773b7fe # 1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          autodiscover: "true"
          log-level: "info"
