# SPDX-License-Identifier: Apache-2.0

name: Semgrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Semgrep
        uses: sentenz/actions/semgrep@bceed480720a7bc304e974cd655ebe42ac41d5e2 # 1.1.9
        with:
          config: "auto"
          metrics: "auto"
          no-secrets-validation: "true"
