# SPDX-License-Identifier: Apache-2.0

name: Semgrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Semgrep
        uses: sentenz/actions/semgrep@99935197a6935a691cb151a3e469f1a969bf7714 # 1.4.2
        with:
          config: "auto"
          metrics: "auto"
          no-secrets-validation: "true"
