# SPDX-License-Identifier: Apache-2.0

name: Semgrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Semgrep
        uses: sentenz/actions/semgrep@1491eeb075bc01903aee09bb3e43bffccf9e6662 # 1.1.4
        with:
          config: "auto"
          metrics: "auto"
          no-secrets-validation: "true"
